import initTabs from './modules/tabs';
import initAccordion from './modules/accordion';
import { initModals, modalConfig } from './modules/modals';
import initSliders from './modules/sliders';
import initToc from './modules/toc';
import {listCategories} from './modules/blog-categories';
import initAddActive from './modules/blog-filter';
import {initForms} from './modules/forms';
import initContactUsForms from './modules/contact-us-form';
import initTitleVideo from './modules/title-video';
import mobileMenu from './modules/header';
import polyfills from './modules/polyfills';
import initAjax from './modules/ajax';
import scroll_to_first_post from './modules/scroll-archive';
import skipTo from './modules/post-skip-to';
import initSeeMore from './modules/see-more';

initSeeMore();
initToc();
listCategories();
initAddActive();
scroll_to_first_post();
// initAjax();
polyfills();
mobileMenu();
initTitleVideo();
initForms();
initContactUsForms();
skipTo();
initTabs();
initAccordion();
initModals();
initSliders();
